variables:
  TEST_DISABLED: "true"

deployment:
  environment:
    url: https://prometheus-blackbox-exporter.dev.ep.shell.com

trigger eng-stage:
  stage: trigger
  trigger:
    project: stage/ep/prometheus-blackbox-exporter
    strategy: depend

include:
  project: dev/ep/release-management
  file: /Jobs/EP-AutoDevops-Template.yml
