variables:
  TEST_DISABLED: "true"

deployment:
  environment:
    url: https://grafana.dev.ep.shell.com

eng-stage:
  stage: trigger
  trigger:
    project: stage/ep/grafana
    strategy: depend

mp2-stage:
  stage: trigger
  trigger:
    project: stage/mp2/pg/grafana
    strategy: depend

include:
  project: dev/ep/release-management
  file: /Jobs/EP-AutoDevops-Template.yml
  ref: registry-token
