{{- if and (.Values.rbac.create) (ne .Values.metadata.namespace "") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.metadata.namespace }}
  name: spark-admin-role
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - "pods"
  verbs:
  - "*"
- apiGroups:
  - "" # "" indicates the core API group
  - "sparkoperator.k8s.io"
  resources:
  - "services"
  - "sparkapplications"
  - "scheduledsparkapplications"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-admin-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.spec.driver.serviceAccount }}
  namespace: {{ .Values.metadata.namespace }}
roleRef:
  kind: Role
  name: spark-admin-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}  