apiVersion: v1
kind: Secret
metadata:
  name: spark-secrets
type: Opaque
data:
  keystore.password: {{ .Values.cred.keystorepwd  }}
  aws.accesskey: {{ .Values.cred.accesskey }} 
  aws.secretkey: {{ .Values.cred.secretkey }}
  aws.path: {{ .Values.cred.awsPath | b64enc | quote }}
  aws.role: {{ .Values.cred.awsRole | b64enc | quote }}
  tsdb.user: {{ .Values.cred.tsdbUser | b64enc | quote }}
  tsdb.password: {{ .Values.cred.tsdbpwd | quote }}
  tsdb.url: {{ .Values.cred.tsdbUrl | b64enc | quote }}
  tsdb.table: {{ .Values.cred.tsdbTable | b64enc | quote }}
  kafka.server: {{ .Values.cred.kafkaServer | b64enc | quote }}
  kafka.topic: {{ .Values.cred.kafkaTopic | b64enc | quote }}
  spark.batchtime: {{ .Values.cred.sparkBatchTime | b64enc | quote }}
  spark.master: {{ .Values.cred.sparkMaster | b64enc | quote }}
  spark.checkpoint: {{ .Values.cred.sparkCheckpoint | b64enc | quote }}
  spark.persist: {{ .Values.cred.sparkPersist | b64enc | quote }}
  spark.startingoffsets: {{ .Values.cred.sparkStartingOffsets | b64enc | quote }}
  message.schema: {{ .Values.cred.messageSchema | b64enc | quote }}